import {StyleSheet} from 'react-native';
import {
  WHITE,
  BLACK,
  CYAN_BLUE,
  PLATINUM,
  LIGHT_GREYISH_RED,
  ORANGE,
  LIGHT_MERCURY,
} from '../../../../styles/colors';
import {CENTER, ROW} from '../../../../styles/constants';
import {fonts} from '../../../../styles/fonts';

export const styles = StyleSheet.create({
  dateTimePicker: {
    backgroundColor: WHITE,
    borderWidth: 1,
    borderColor: LIGHT_MERCURY,
    borderRadius: 8,
    height: 42,
  },
  theme: {colors: {text: BLACK}},
  dateAndTime: {
    minHeight: 42,
    marginVertical: '3%',
    marginHorizontal: '3%',
  },
  dateTimeStyles: {
    marginVertical: '2%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
  },
  border: {
    marginLeft: '3%',
    marginRight: '3%',
    shadowColor: WHITE,
    shadowOpacity: '15%',
    shadowColor: BLACK,
    borderRadius: 10,
    backgroundColor: WHITE,
    elevation: 10,
  },
  TitleStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '3%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  inputTextStyle: {
    borderBottomWidth: 1,
    borderColor: PLATINUM,
    backgroundColor: LIGHT_GREYISH_RED,
    marginBottom: 15,
    color: BLACK,
    margin: '3%',
    padding: 10,
    borderRadius: 6,
  },
  ScrollViewContainerStyle: {
    paddingBottom: '20%',
  },
  buttonStyles: {
    marginVertical: '20%',
    marginHorizontal: '4%',
    height: 48,
    borderRadius: 8,
    justifyContent: CENTER,
    alignItems: CENTER,
    backgroundColor: ORANGE,
  },
  Description: {
    marginTop: '5%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
    marginLeft: '3%',
  },
  textInputStyle: {
    borderBottomWidth: 1,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
    borderColor: PLATINUM,
    backgroundColor: LIGHT_GREYISH_RED,
    marginBottom: 17,
    color: BLACK,
    margin: '3%',
    padding: 10,
    borderRadius: 6,
  },
  ContentStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '15%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
  },
  NameStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '15%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  ContentHeading: {
    marginTop: '5%',
    marginBottom: '5%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
    marginLeft: '3%',
  },
  Image: {
    height: 48,
    width: 48,
    alignSelf: CENTER,
    borderRadius: 24,
  },
  ImageStyle: {
    flexDirection: ROW,
    marginLeft: '3%',
  },
  buttonTextStyle: {
    color: WHITE,
    fontFamily: fonts.family.rubik700,
    fontSize: fonts.size.fontSize16,
    marginHorizontal: 10,
  },
  boxStyles: {
    marginLeft: '3%',
    marginRight: '3%',
    borderColor: LIGHT_MERCURY,
    marginBottom: 15,
    color: LIGHT_GREYISH_RED,
    paddingLeft: 13,
  },
});
