export const PLAN_DETAILS = 'Plan Details';
export const PLAN_MEMBERS = 'Plan Members';
export const ADD_MEMBER = 'Add Member';
export const RELATIONSHIP = 'Relationship';
export const ADD_NEW_MEMBER = 'Add New Member';
export const CANNOT_ADD_MEMBERS = 'Cannot add any further members as plan has been locked';
export const ALERT = 'Alert';
export const TRY_AGAIN = 'Relations being fetched. Please try again';
export const NO_RELATIONS = 'No Active relations left for this plan';
export const ERROR_TEXT = 'Unable to fetch relatives';
export const PLAN_LOCKED = 'Plan has been locked';
export const PLEASE_SELECT_MEMBERS = 'Please select members';
export const LOCK_PLAN = 'Are you sure want to lock the plan?';
export const CHILDREN_ALERT = (count) => `Plan only supports ${count} children`;
export const OK = 'Ok';
export const CANCEL = 'Cancel';
export const SON = 'Son';
export const DAUGHTER = 'Daughter';