import {StyleSheet} from 'react-native';
import {
  DARK_BLUE,
  PLATINUM,
  FLASH_WHITE,
  WHITE,
  BLACK,
  CYAN_BLUE,
  LIGHT_GREYISH_RED,
  DARK_GREY,
  ORANGE,
  LIGHT_MERCURY,
  RED,
} from '../../../../styles/colors';
import {CENTER, ROW} from '../../../../styles/constants';
import {fonts} from '../../../../styles/fonts';
export const styles = StyleSheet.create({
  theme: {colors: {text: BLACK}},
  textInputStyle: {
    borderBottomWidth: 1,
    borderColor: PLATINUM,
    backgroundColor: LIGHT_GREYISH_RED,
    marginBottom: 15,
    color: BLACK,
    margin: '3%',
    borderRadius: 6,
  },
  dateTimePicker: {
    backgroundColor: {FLASH_WHITE},
  },
  boxStyles: {
    marginLeft: '3%',
    marginRight: '3%',
    borderColor: LIGHT_MERCURY,
    marginBottom: 15,
    color: LIGHT_GREYISH_RED,
  },
  dateAndTime: {
    marginTop: 10,
    marginLeft: '3%',
    marginRight: '3%',
    minHeight: 42,
    marginBottom: 15,
  },
  Date: {
    marginTop: '10%',
    marginBottom: '5%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
  },
  Time: {
    marginTop: '5%',
    marginBottom: '5%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
  },
  ContentHeading: {
    marginTop: '5%',
    marginBottom: '5%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
    marginLeft: '3%',
  },
  ContentStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '15%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
  },
  Description: {
    marginTop: '10%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
    marginLeft: '3%',
  },
  TitleStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '3%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  NameStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '15%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  border: {
    marginLeft: '3%',
    marginRight: '3%',
    shadowColor: WHITE,
    shadowOpacity: '15%',
    borderRadius: 10,
    backgroundColor: WHITE,
  },
  dateTimePicker: {
    minHeight: 22,
    backgroundColor: LIGHT_MERCURY,
  },
  theme: {colors: {text: DARK_GREY}},
  ImageStyle: {
    flexDirection: ROW,
    marginLeft: '5%',
  },
  Image: {
    height: 48,
    width: 48,
    alignSelf: CENTER,
  },
});
