import {StyleSheet} from 'react-native';
import {
  PLATINUM,
  WHITE,
  BLACK,
  ORANGE,
  CYAN_BLUE,
  LIGHT_GREYISH_RED,
  LIGHT_MERCURY,
} from '../../../../styles/colors';
import {CENTER, ROW} from '../../../../styles/constants';
import {fonts} from '../../../../styles/fonts';
export const styles = StyleSheet.create({
  theme: {colors: {text: BLACK}},
  textInputStyle: {
    borderBottomWidth: 1,
    borderColor: PLATINUM,
    backgroundColor: LIGHT_GREYISH_RED,
    marginBottom: 15,
    color: BLACK,
    margin: '3%',
    borderRadius: 6,
    paddingLeft: 13,
    minHeight:50,
  },
  boxStyles: {
    marginHorizontal:12,
    borderColor: LIGHT_MERCURY,
    color: LIGHT_GREYISH_RED,
    backgroundColor: LIGHT_GREYISH_RED,
    paddingLeft: 13,
  },
  backGroundStyle: {backgroundColor: WHITE},
  dropStyles: {
    marginHorizontal: 13,
    borderColor: LIGHT_MERCURY,
  },
  dateAndTime: {
    minHeight: 42,
    marginVertical: '3%',
    marginHorizontal: '3%',
  },

  dateTimeStyles: {
    marginVertical: '2%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
  },
  valueStyle: {
    alignSelf: CENTER,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
    color: ORANGE,
  },
  ContentHeading: {
    marginTop: '5%',
    marginBottom: '5%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
    marginLeft: '3%',
  },
  ContentStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '15%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
  },
  Description: {
    marginTop: '4%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
    marginLeft: '3%',
  },
  TitleStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '3%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  NameStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '15%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  border: {
    marginLeft: '3%',
    marginRight: '3%',
    shadowColor: WHITE,
    shadowOpacity: 0.25,
    shadowColor: BLACK,
    borderRadius: 10,
    backgroundColor: WHITE,
    elevation: 10,
    paddingVertical:8,
    zIndex:10,
    shadowOffset: {width:0,height:0}
  },
  borderSelect: {
    marginLeft: '3%',
    marginRight: '3%',
    shadowColor: WHITE,
    shadowOpacity: 0.25,
    shadowColor: BLACK,
    borderRadius: 10,
    backgroundColor: WHITE,
    elevation: 10,
    paddingBottom: 10,
    zIndex:10,
    shadowOffset: {width:0,height:0}
  },
  dateTimePicker: {
    backgroundColor: WHITE,
    borderWidth: 1,
    borderColor: LIGHT_MERCURY,
    borderRadius: 8,
    height: 42,
  },
  ImageStyle: {
    flexDirection: ROW,
    marginLeft: '3%',
  },
  Image: {
    height: 48,
    width: 48,
    alignSelf: CENTER,
    borderRadius: 24,
  },
});
