import { StyleSheet } from 'react-native';
import { BLUE_GRAY, BOX_SHADOW, CHARCOAL, CYAN_BLUE, DARK_GRAY, DEEP_BLUE, GREEN, GREY70, ORANGE, VERY_LIGHT_GREY, V_LIGHT_GREY, WHITE } from '../../../../styles/colors'
import { ABSOLUTE, CENTER, FLEX_END, ROW, SPACE_BETWEEN } from '../../../../styles/constants';
import { fonts } from '../../../../styles/fonts'

export const styles = StyleSheet.create({
    contentContainerStyle: {
        flexGrow: 1,
        paddingBottom: 400,
    },
    circle: {
        marginLeft: 41,
        width: "80%",
        flexDirection: ROW,
        justifyContent: SPACE_BETWEEN,
    },
    progressBar: {
        marginTop: 30,
        flexDirection: ROW,
    },
    PaymentCircle: {
        minWidth: 12,
        minHeight: 12,
        borderRadius: 15,
        borderWidth: 1,
        color: V_LIGHT_GREY,

    },
    circles:{
        minWidth: 12,
        minHeight: 12,
        borderRadius: 15,
        borderWidth: 1.2,
        borderColor:GREEN,
    },
    tickMark: {
        color: GREEN,
        width: "25%",
        height: "60%",
        marginLeft: "30%",
        marginTop: "11%",
        borderBottomWidth: 2,
        borderRightWidth: 2,
        borderRightColor: GREEN,
        borderBottomColor: GREEN,
        position: ABSOLUTE,
        transform: [{ rotateX: '45deg' }, { rotateZ: '45deg' }],
    },
    Line: {
        marginTop: 5,
        width: 1,
        height: 1,
        backgroundColor: GREEN,
        flex: 1,
    },
    border: {
        marginTop: 14,
        marginLeft: 16,
        minHeight: "12%",
        marginRight: 16,
        shadowColor: WHITE,
        shadowOpacity: "5%",
        borderRadius: 12,
        backgroundColor: WHITE,
        dropShadow: BOX_SHADOW,
        elevation: 5,
        shadowColor: VERY_LIGHT_GREY,

    },
    checkboxAddress: {
        alignItems: FLEX_END,
        marginRight: 19,
        marginTop: "4.5%",
    },
    adressName: {
        marginBottom: "1%",
        marginLeft: 19,
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize12,

    },
    Images: {
        justifyContent: SPACE_BETWEEN,
        flexDirection: ROW,
        marginRight: 25,
    },
    adressCheck: {
        marginTop: 11,
        marginLeft: 19,
        marginBottom: 15,
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize14,
    },
    TextPrice: {
        marginLeft: 26,
        marginTop: 20,
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize14,
    },
    line: {
        marginTop: 20,
        borderWidth: 0.2,
        marginLeft: 24,
        width: "85%",
        borderColor: GREY70,
    },
    orderPrice: {
        marginLeft: 26,
        marginTop: 15,
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize16,
    },
    OrderAmountDirection: {
        flexDirection: ROW,
    },
    orderAmount: {
        marginLeft: 151,
        marginTop: 15,
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize16,
    },
    Input: {
        borderColor: GREY70,
        borderWidth: 1,
        borderRadius: 12,
        marginLeft: 24,
        marginTop: 35,
        minHeight: 40,
        width: "60%",
    },
    Apply: {
        marginLeft: 27,
        color: WHITE,
        marginTop: 10,

    },
    ApplyCoupon: {
        alignItems: CENTER,
        borderWidth: 0.5,
        borderRadius: 12,
        minHeight: 40,
        width: 100,
        marginTop: 35,
        alignSelf: CENTER,
        backgroundColor: ORANGE,
        borderColor: GREY70,
    },
    Amountpyable: {
        marginLeft: 26,
        marginTop: 21,
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik600,
        fontSize: fonts.size.fontSize16,
    },
    payableAmount: {
        marginLeft: 151,
        marginTop: 15,
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik600,
        fontSize: fonts.size.fontSize16,
    },
    touchableButton: {
        backgroundColor: ORANGE,
        marginTop: 20,
        marginHorizontal: 13,
        paddingHorizontal: 15,
        borderRadius: 8,
        alignItems: CENTER,
    },
    tobePaid: {
        justifyContent: CENTER,
        paddingVertical: 15,
        color: WHITE,
        fontFamily: fonts.family.rubik500,
        fontSize: fonts.size.fontSize16,
    },
    termsAndCondtion: {
        marginTop: 20,
        marginLeft: 12,
        marginRight: 56,
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize10,
    },
    checkBoxContainer: {
        marginLeft: 24,
        width: 13,
        minHeight: 13,
        marginTop: 20,
        borderWidth: 1,
        borderColor: CYAN_BLUE,
        marginRight: 12,
    },
    AddText: {
        marginLeft: '6%',
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik600,
        fontSize: fonts.size.fontSize10,
        color: GREEN,
    },
    check: {
        marginRight: '6%',
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik600,
        fontSize: fonts.size.fontSize10,
    },
    progress: {
        justifyContent: SPACE_BETWEEN,
        flexDirection: ROW,
    },
    progressView: {
        width: '90%',
        justifyContent: CENTER,
        alignSelf: CENTER,
        marginTop: 20,
        marginLeft: 10,
    },
    couponContainer: {
        flexDirection: ROW,
        justifyContent: SPACE_BETWEEN,
        padding: 5,
        marginVertical:25,
        marginHorizontal:16
      },
      crossStyle: {
        color: DARK_GRAY,
        fontFamily: fonts.family.rubik600,
        fontSize: fonts.size.fontSize16,
      },
      iconStyle: {
        color: CHARCOAL,
      },
      appliedStyle: {
        color: DEEP_BLUE,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize16,
      },
      descStyle: {
        height: 36,
        width: '60%',
        borderRadius: 5,
        paddingLeft: 16,
        paddingRight: 12,
        justifyContent: SPACE_BETWEEN,
        alignItems: CENTER,
        flexDirection: ROW,
        backgroundColor: BLUE_GRAY,
      },
      couponDiscountStyle: {
        height: 36,
        color:GREEN,
        paddingVertical:10,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize14,
        paddingHorizontal:5,
      },
})