import {StyleSheet} from 'react-native';
import {
  DARK_BLUE,
  WHITE,
  CYAN_BLUE,
  GREY,
  ORANGE,
  RED_SHADE,
  GREEN,
  BLACK,
  BOX_SHADOW,
  LIGHT_MERCURY,
  LIGHT_GREYISH_RED,
} from '../styles/colors';
import {
  COLUMN,
  ROW,
  SPACE_BETWEEN,
  CENTER,
  FLEX_END,
  ABSOLUTE,
  FLEX_START,
} from '../styles/constants';
import {fonts} from '../styles/fonts';

export const styles = StyleSheet.create({
  Image: {
    height: 48,
    width: 48,
    alignSelf: 'center',
    marginLeft: 20,
  },
  buttonStyle: {
    backgroundColor: ORANGE,
    height: 48,
    marginLeft: '3%',
    marginRight: '3%',
  },
  text: {
    color: WHITE,
    alignSelf: CENTER,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize16,
  },
  ContentStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '3%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
  },
  NameStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '3%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  ImageStyle: {
    flexDirection: ROW,
    marginLeft: '5%',
  },
  Image: {
    height: 48,
    width: 48,
    marginTop: '40%',
    marginLeft: '10%',
  },
  CompleteView: {
    backgroundColor: WHITE,
    marginLeft: '5%',
    marginRight: '5%',
    marginTop: '5%',
    marginBottom: '5%',
    height: 139,
    width: '90%',
    borderRadius: 10,
  },
  Button: {
    backgroundColor: CYAN_BLUE,
    height: 31,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  buttonView: {
    marginTop: 18,
  },
  ButtonText: {
    color: WHITE,
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize10,
    alignSelf: CENTER,
    marginTop: '3%',
  },
  Top: {
    flexDirection: ROW,
    margintop: '5%',
  },
  Add: {
    flex: 1,
  },
  Location: {
    flexDirection: ROW,
    marginLeft: '3%',
    color: BLACK,
  },

  Cont: {
    flexDirection: ROW,
    justifyContent: SPACE_BETWEEN,
  },
  Year: {
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize10,
    marginRight: '5%',
    marginTop: '5%',
  },
  Address: {
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize10,
  },
  labTest: {
    flexDirection: COLUMN,
    marginLeft: 18,
    marginRight: 24,
    marginTop: 16,
    flex: 1,
    justifyContent: SPACE_BETWEEN,
  },

  available: {
    flexDirection: ROW,
  },
  BookingCard: {
    marginTop: 28,
    borderRadius: 6,
    height: 137,
    backgroundColor: WHITE,
    marginLeft: 14,
    marginRight: 15,
  },
  customId: {
    flexDirection: ROW,
    justifyContent: SPACE_BETWEEN,
  },
  custom: {
    marginRight: 13,
    marginTop: 6,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize8,
  },
  status: {
    marginTop: 11,
    marginLeft: 11,
    flexGrow: 1,
  },
  initiatedColor: {
    color: ORANGE,
    fontFamily: fonts.family.rubik500,
  },
  cancelledColor: {
    color: RED_SHADE,
    fontFamily: fonts.family.rubik500,
  },
  confirmedColor: {
    color: GREEN,
    fontFamily: fonts.family.rubik500,
  },
  lab: {
    flexDirection: ROW,
    justifyContent: SPACE_BETWEEN,
  },
  labs: {
    color: CYAN_BLUE,
    marginTop: 10,
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize14,
  },
  date: {
    marginRight: 13,
    marginTop: 10,
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize8,
  },
  description: {
    color: CYAN_BLUE,
    marginTop: 16,
    fontFamily: fonts.family.rubik500,
  },
  reschedule: {
    flexDirection: ROW,
    justifyContent: SPACE_BETWEEN,
    marginTop: 50,
    fontFamily: fonts.family.rubik500,
    marginLeft: 17.3,
    marginRight: 34,
  },
  cards: {
    backgroundColor: WHITE,
    height: 76,
    marginTop: 19,
    marginLeft: 13,
    marginRight: 14,
    borderRadius: 12,
  },
  image: {
    height: 24,
    width: 24,
  },
  packageTest: {
    color: DARK_BLUE,
    fontSize: fonts.size.fontSize12,
    justifyContent: CENTER,
    marginBottom: 10,
    fontFamily: fonts.family.rubik500,
  },
  booking: {
    flexDirection: ROW,
  },
  download: {
    marginLeft: 160,
    marginTop: 2,
    color: DARK_BLUE,
    fontSize: fonts.size.fontSize12,
    fontFamily: fonts.family.rubik500,
  },
  carouselText: {
    marginLeft: 17,
    marginTop: 11,
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik700,
    fontSize: fonts.size.fontSize16,
    height: 21,
  },
  line: {
    borderBottomColor: GREY,
    borderBottomWidth: 1,
    width: 246,
    marginLeft: 35,
    marginTop: 19,
  },
  lineJustify: {
    alignItems: CENTER,
    flexDirection: ROW,
    justifyContent: SPACE_BETWEEN,
  },
  carouselMain: {
    justifyContent: CENTER,
    marginTop: 16,
    marginLeft: 14,
    marginRight: 15,
    alignItems: CENTER,
  },
  flatlist: {
    flexDirection: ROW,
    marginTop: 20,
  },
  imageStyle: {
    width: 49,
    height: 50,
    marginVertical: '3%',
    marginLeft: 19,
  },
  viewContainer: {
    flexGrow: 1,
    borderRadius: 6,
    marginLeft: 13,
    marginRight: 14,
    backgroundColor: WHITE,
    borderWidth: 1,
    borderColor: WHITE,
    marginTop: 28,
  },
  buttonStyle: {
    height: 32,
    backgroundColor: ORANGE,
    borderRadius: 8,
    marginTop: 17,
    margin: 11,
    justifyContent: CENTER,
  },
  head: {
    alignSelf: FLEX_START,
    marginLeft: 9,
    shadowColor: WHITE,
    position: ABSOLUTE,
    top: -11,
    fontSize: 14,
    color: CYAN_BLUE,
    paddingLeft: 6,
    paddingRight: 6,
    fontSize: fonts.size.fontSize14,
    fontFamily: fonts.family.rubik400,
  },
  textStyle: {
    color: WHITE,
    alignSelf: CENTER,
  },
  sideBySide: {
    flexDirection: ROW,
    marginTop: 15,
  },
  text1: {
    alignSelf: CENTER,
    margin: '4%',
  },
  textColor: {
    color: CYAN_BLUE,
  },
  Available: {
    marginLeft: 11,
    marginTop: 15,
    color: CYAN_BLUE,
    fontSize: fonts.size.fontSize12,
    fontFamily: fonts.family.rubik400,
  },
  expiry: {
    alignSelf: FLEX_END,
    marginTop: 18,
    marginRight: 11,
    marginTop: 11,
    color: CYAN_BLUE,
    fontSize: fonts.size.fontSize8,
    fontFamily: fonts.family.rubik400,
  },
  StatusColor:{
    color:RED_SHADE,
    backgroundColor:RED_SHADE
  },
  booked: {
    marginTop: 22,
    marginLeft: 16,
    color: ORANGE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  AddNewAddress: {
    marginTop: 30,
    marginLeft: 16,
    marginRight: 140,
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  border: {
    borderWidth: 0.2,
    marginTop: 14,
    marginLeft: 16,
    marginRight: 16,
    shadowColor: WHITE,
    shadowOpacity: "5%",
    borderRadius: 6,
    backgroundColor: WHITE,
    dropShadow: BOX_SHADOW,

  },
  AddAddressLine: {
    marginTop: 16,
    marginLeft: 12,
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
  },
  textInputStyle: {
    borderWidth: 1,
    borderColor: LIGHT_MERCURY,
    backgroundColor: LIGHT_GREYISH_RED,
    borderRadius: 6,
    marginBottom: 11,
    color: DARK_BLUE,
    minHeight: 42,
    marginLeft: 12,
    marginRight: 26,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize14,
  },
  boxStyles: {
    marginLeft: 12,
    marginRight: 26,
    borderWidth: 0.1,
    backgroundColor: LIGHT_GREYISH_RED,
    borderColor: LIGHT_MERCURY,
    minHeight: 42,
    borderRadius: 2,
    marginBottom: 31
  },
  touchableButton: {
    backgroundColor: ORANGE,
    marginTop: 34,
    marginLeft: 16,
    marginRight: 16,
    borderRadius: 8,
    minHeight: 48
  },
  textBook: {
    textAlign: CENTER,
    color: WHITE,
    fontFamily: fonts.family.rubik600,
    marginLeft:"6%",
    marginTop: 12,
    fontSize: fonts.size.fontSize16,

  },
});
