import {StyleSheet} from 'react-native';
import {
  DARK_BLUE,
  WHITE,
  CYAN_BLUE,
  GREY,
  ORANGE,
  RED_SHADE,
  GREEN,
  BLACK,
  BOX_SHADOW,
  LIGHT_MERCURY,
  LIGHT_GREYISH_RED,
  RED,
  VERY_LIGHT_GREY,
  BIANCA,
} from '../styles/colors';
import {
  COLUMN,
  ROW,
  SPACE_BETWEEN,
  CENTER,
  FLEX_END,
  ABSOLUTE,
  FLEX_START,
} from '../styles/constants';
import {fonts} from '../styles/fonts';
import {getDimensions} from '../utils/utils';
const {width} = getDimensions();
export const styles = StyleSheet.create({
  buttonStyle: {
    backgroundColor: ORANGE,
    height: 48,
    marginLeft: '3%',
    marginRight: '3%',
    borderRadius: 8,
    alignItems: CENTER,
    justifyContent: CENTER,
    marginVertical: 31,
  },
  text: {
    color: WHITE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize16,
  },
  ContentStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '3%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
  },
  NameStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '3%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  ImageStyle: {
    flexDirection: ROW,
    marginLeft: '5%',
  },
  Image: {
    height: 48,
    width: 48,
    marginTop: '16%',
    marginLeft: '12%',
    // paddingLeft: '12%',
    borderRadius: 24,
  },
  CompleteView: {
    backgroundColor: WHITE,
    marginLeft: '5%',
    marginRight: '5%',
    marginTop: '10%',
    marginBottom: '5%',
    height: 109,
    width: '90%',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  Button: {
    backgroundColor: CYAN_BLUE,
    height: 31,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  buttonView: {
    marginTop: 4,
  },
  ButtonText: {
    color: WHITE,
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize10,
    alignSelf: CENTER,
    marginTop: '3%',
  },
  Top: {
    flexDirection: ROW,
    margintop: '5%',
  },
  Add: {
    flex: 1,
  },
  Location: {
    flexDirection: ROW,
    marginLeft: '3%',
    color: BLACK,
  },

  Cont: {
    flexDirection: ROW,
    justifyContent: SPACE_BETWEEN,
  },
  Year: {
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize10,
    marginRight: '5%',
    marginTop: '5%',
  },
  Address: {
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize10,
  },
  labTest: {
    flexDirection: COLUMN,
    marginLeft: 18,
    marginRight: 24,
    marginTop: 16,
    flex: 1,
    justifyContent: SPACE_BETWEEN,
  },

  available: {
    flexDirection: ROW,
  },
  textSpacing: {
    marginHorizontal: 5,
  },
  BookingCard: {
    marginTop: 28,
    borderRadius: 6,
    height: 137,
    backgroundColor: WHITE,
    marginLeft: 14,
    marginRight: 15,
  },
  customId: {
    flexDirection: ROW,
    justifyContent: SPACE_BETWEEN,
  },
  custom: {
    marginRight: 13,
    marginTop: 6,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize8,
  },
  status: {
    marginTop: 11,
    marginLeft: 11,
    flexGrow: 1,
  },
  initiatedColor: {
    color: ORANGE,
    fontFamily: fonts.family.rubik500,
  },
  cancelledColor: {
    color: RED_SHADE,
    fontFamily: fonts.family.rubik500,
  },
  confirmedColor: {
    color: GREEN,
    fontFamily: fonts.family.rubik500,
  },
  lab: {
    flexDirection: ROW,
    justifyContent: SPACE_BETWEEN,
  },
  labs: {
    color: CYAN_BLUE,
    marginTop: 10,
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize14,
  },
  date: {
    marginRight: 13,
    marginTop: 10,
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize8,
  },
  description: {
    color: CYAN_BLUE,
    marginTop: 16,
    fontFamily: fonts.family.rubik500,
  },
  reschedule: {
    flexDirection: ROW,
    justifyContent: SPACE_BETWEEN,
    marginTop: 50,
    fontFamily: fonts.family.rubik500,
    marginHorizontal: 34,
  },
  cards: {
    backgroundColor: WHITE,
    height: 76,
    marginTop: 19,
    marginLeft: 13,
    marginRight: 14,
    borderRadius: 12,
  },
  image: {
    height: 24,
    width: 24,
  },
  packageTest: {
    color: DARK_BLUE,
    fontSize: fonts.size.fontSize12,
    justifyContent: CENTER,
    marginBottom: 10,
    fontFamily: fonts.family.rubik500,
  },
  booking: {
    flexDirection: ROW,
  },
  download: {
    marginLeft: 160,
    marginTop: 2,
    color: DARK_BLUE,
    fontSize: fonts.size.fontSize12,
    fontFamily: fonts.family.rubik500,
  },
  carouselText: {
    marginLeft: 17,
    marginTop: 11,
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik700,
    fontSize: fonts.size.fontSize16,
    height: 21,
  },
  line: {
    borderBottomColor: GREY,
    borderBottomWidth: 1,
    width: 246,
    marginLeft: 35,
    marginTop: 19,
  },
  lineJustify: {
    alignItems: CENTER,
    flexDirection: ROW,
    justifyContent: SPACE_BETWEEN,
  },
  carouselMain: {
    justifyContent: CENTER,
    marginTop: 16,
    marginLeft: 14,
    marginRight: 15,
    alignItems: CENTER,
  },
  flatlist: {
    flexDirection: ROW,
    marginTop: 20,
  },
  imageStyle: {
    width: 49,
    height: 50,
    marginVertical: '3%',
    marginLeft: 19,
  },
  viewContainer: {
    flexGrow: 1,
    borderRadius: 6,
    marginLeft: 13,
    marginRight: 14,
    backgroundColor: WHITE,
    borderWidth: 1,
    borderColor: WHITE,
    marginTop: 28,
  },
  buttonStyleMyTest: {
    minHeight: 48,
    backgroundColor: ORANGE,
    borderRadius: 6,
    marginTop: 17,
    justifyContent: CENTER,
  },
  head: {
    alignSelf: FLEX_START,
    marginHorizontal: 19,
    shadowColor: WHITE,
    position: ABSOLUTE,
    fontSize: 14,
    color: CYAN_BLUE,
    paddingHorizontal: 6,
    fontSize: fonts.size.fontSize14,
    fontFamily: fonts.family.rubik400,
  },
  textStyle: {
    color: WHITE,
    alignSelf: CENTER,
    fontSize: fonts.size.fontSize14,
    fontFamily: fonts.family.rubik500,
  },
  sideBySide: {
    flexDirection: ROW,
    marginTop: 15,
  },
  text1: {
    alignSelf: CENTER,
    margin: '4%',
  },
  textColor: {
    color: CYAN_BLUE,
  },
  Available: {
    marginLeft: 11,
    marginTop: 15,
    color: CYAN_BLUE,
    fontSize: fonts.size.fontSize12,
    fontFamily: fonts.family.rubik400,
  },
  expiry: {
    alignSelf: FLEX_END,
    marginRight: 11,
    bottom: 9,
    color: CYAN_BLUE,
    fontSize: fonts.size.fontSize8,
    fontFamily: fonts.family.rubik400,
  },
  StatusColor: {
    color: RED_SHADE,
    backgroundColor: RED_SHADE,
  },
  booked: {
    marginTop: 22,
    marginLeft: 16,
    color: ORANGE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  AddNewAddress: {
    marginTop: 30,
    marginLeft: 16,
    marginRight: 140,
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  AddAddressLine: {
    marginTop: 16,
    marginBottom: 8,
    marginLeft: 14,
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
  },
  textInputStyle: {
    paddingLeft: 12,
    marginHorizontal: 13,
    borderWidth: 1,
    borderColor: LIGHT_MERCURY,
    backgroundColor: LIGHT_GREYISH_RED,
    borderRadius: 6,
    marginBottom: 11,
    color: DARK_BLUE,
    minHeight: 42,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize14,
  },
  boxStyles: {
    marginHorizontal: 13,
    borderWidth: 0.1,
    backgroundColor: LIGHT_GREYISH_RED,
    borderColor: LIGHT_MERCURY,
    minHeight: 42,
    borderRadius: 8,
    marginBottom: 31,
  },
  touchableButton: {
    justifyContent: CENTER,
    backgroundColor: ORANGE,
    marginTop: 34,
    marginLeft: 16,
    marginRight: 16,
    borderRadius: 8,
    minHeight: 48,
  },
  textBook: {
    textAlign: CENTER,
    color: WHITE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize16,
  },
  contentContainerStyle: {
    flexGrow: 1,
    paddingBottom: 10,
  },
  tobePaid: {
    textAlign: CENTER,
    paddingTop: 15,
    paddingBottom: 15,
    color: WHITE,
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize16,
  },
  AddressCheck: {
    width: '96%',
    flexDirection: ROW,
  },
  selectDate: {
    marginTop: 30,
    marginLeft: 16,
    flex: 1,
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  AddNewAdd: {
    marginLeft: 38,
    marginTop: 18,
    borderRadius: 8,
    backgroundColor: WHITE,
    flexDirection: ROW,
    shadowColor: GREY,
    elevation: 10,
  },
  addNew: {
    alignItems: CENTER,
    marginRight: 15,
    marginLeft: 7.33,
    minHeight: 25,
    marginTop: 9,
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize12,
  },
  svg: {
    marginTop: 9,
    marginLeft: 7.33,
  },
  border: {
    elevation: 5,
    marginTop: 14,
    marginHorizontal: 16,
    shadowColor: GREY,
    borderRadius: 12,
    backgroundColor: WHITE,
    dropShadow: BOX_SHADOW,
  },
  borderAddNewAddress: {
    elevation: 5,
    marginTop: 14,
    marginHorizontal: 16,
    shadowColor: GREY,
    backgroundColor: WHITE,
    dropShadow: BOX_SHADOW,
    shadowColor: WHITE,
    shadowOpacity: '5%',
    borderRadius: 6,
  },
  checkboxAddress: {
    justifyContent: SPACE_BETWEEN,
    flexDirection: ROW,
    marginRight: 19,
    marginTop: 8,
  },
  adressName: {
    width: '80%',
    marginTop: 10,
    marginHorizontal: 19,
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
  },
  CityName: {
    marginTop: 5,
    marginHorizontal: 19,
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
  },
  AddressImages: {
    justifyContent: SPACE_BETWEEN,
    flexDirection: ROW,
    marginTop: 20,
    marginRight: 25,
  },
  AdressCheckBox: {
    marginTop: 5,
    marginHorizontal: 19,
    marginBottom: 15,
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize14,
  },
  SvgImage: {
    flex: 1,
  },
  AddText: {
    marginLeft: '6%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize10,
  },
  check: {
    marginRight: '6%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize10,
  },
  progress: {
    justifyContent: SPACE_BETWEEN,
    flexDirection: ROW,
  },
  errorContact: {
    color: RED,
    marginHorizontal: 14,
  },
  dateAndTimeStyle: {
    fontSize: fonts.size.fontSize8,
    fontFamily: fonts.family.rubik500,
  },
  containerView: {
    width: '100%',
    backgroundColor: WHITE,
    elevation: 2,
    shadowOpacity: 0.2,
    shadowColor: BLACK,
    marginVertical: '3%',
    borderRadius: 6,
  },
  StatusAndDoctorStyle: {
    flexDirection: ROW,
    justifyContent: SPACE_BETWEEN,
  },
  statusText: {
    color: ORANGE,
    fontSize: fonts.size.fontSize12,
    fontFamily: fonts.family.rubik500,
  },
  leftView: {
    width: '70%',
  },
  rightView: {
    alignItems: FLEX_END,
    width: '30%',
  },
  doctorNameText: {
    color: CYAN_BLUE,
    fontSize: fonts.size.fontSize12,
    fontFamily: fonts.family.rubik500,
  },
  doctorSpecialityText: {
    marginTop: '8%',
    color: CYAN_BLUE,
    fontSize: fonts.size.fontSize10,
    fontFamily: fonts.family.rubik400,
  },
  HospView: {
    justifyContent: SPACE_BETWEEN,
    flexDirection: ROW,
    width: '100%',
    marginTop: 20,
  },
  HospitalViewStyle: {
    marginTop: '4%',
  },
  HospNameStyle: {
    flexDirection: ROW,
  },
  HospNameText: {
    color: CYAN_BLUE,
    fontSize: fonts.size.fontSize14,
    fontFamily: fonts.family.rubik500,
  },
  LocationStyle: {
    color: CYAN_BLUE,
    fontSize: fonts.size.fontSize14,
  },
  DescriptionText: {
    color: CYAN_BLUE,
    fontSize: fonts.size.fontSize10,
    fontFamily: fonts.family.rubik400,
    marginTop: '10%',
  },
  CalView: {
    marginTop: '20%',
    flexDirection: ROW,
    alignItems: CENTER,
  },
  CalenderStyle: {
    color: BLACK,
    fontSize: fonts.size.fontSize24,
  },
  ButtonStyle: {
    flexDirection: ROW,
    justifyContent: SPACE_BETWEEN,
  },
  totalView: {
    flexDirection: ROW,
    flex: 1,
    marginVertical: '3%',
    marginHorizontal: '3%',
  },
  rightSubView: {
    alignItems: FLEX_END,
  },
  headView: {
    justifyContent: CENTER,
    alignItems: CENTER,
    marginLeft: 19,
    bottom: 9,
    width: '44%',
    minHeight: 20,
    borderRadius: 6,
    backgroundColor: BIANCA,
  },
  direction: {
    paddingHorizontal: 15,
    marginTop: '2%',
    flexDirection: ROW,
    alignSelf: FLEX_END,
  },
  dateStyle: {
    marginTop: '5%',
    marginLeft: 5,
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize10,
  },
  timeStyle: {
    marginTop: '5%',
    marginLeft: 5,
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize4,
  },
  carView: {
    backgroundColor: WHITE,
    shadowOpacity: 1,
    shadowColor: BLACK,
    minHeight: 117,
    width: width - 30,
    borderRadius: 6,
  },
  carDoctorNameText: {
    color: ORANGE,
    fontSize: fonts.size.fontSize14,
    fontFamily: fonts.family.rubik400,
    marginRight: '3%',
  },
  overallView: {
    flex: 1,
    marginTop: 15,
    marginHorizontal: '4%',
  },
  HospitalName: {
    color: DARK_BLUE,
    fontSize: fonts.size.fontSize16,
    fontFamily: fonts.family.rubik400,
    marginTop: 12,
  },
  CancelReschedule: {
    fontSize: fonts.size.fontSize12,
    fontFamily: fonts.family.rubik400,
  },
  RescCancel: {
    marginHorizontal: '3%',
    marginBottom: '3%',
  },
  RescheduleCancel: {
    marginTop: '5%',
  },
  HospitalStyle: {
    position: ABSOLUTE,
    right: '5%',
    top: '65%',
    fontSize: fonts.size.fontSize10,
    fontFamily: fonts.family.rubik400,
  },
});
