export const THANK_YOU="Thank You for Booking Appointment with us.";
export const YOUR_PIN='Your PIN for this appointment is - '
export const HOPE_YOUR_APPOINTMENT ="Hope your appointment went well.Please share your PIN with the Hospital Admin to complete your appointment.";
export const RESCHEDULE_APPOINTMENT="Reschedule Appointment";
export const DOCTOR="Doctor";
export const SPECIALIZATION="Specialization";
export const DESCRIPTION="Description";
export const BOOK_AN_APPOINTMENT=" Book An Appointment";
export const CANCEL="cancel";
export const RESCHEDULE ="Reschedule";
export const CHECK="Check In";