export const PRICE_DETAILS="Price Details";
export const ORDER_AMOUNT="Order Amount";
export const RUPEE="₹ ";
export const COUPON="Coupon Code";
export const APPLY="Apply";
export const DISCOUNT="Discount";
export const TEST_AND_PACKAGES_PRICE="Price";
export const AMOUNT_PAYABLE="Amount Payable";
export const QUANTITY = (item) =>`Quantity ${item}`;
export const BY_CLICKING="By clicking on the below button, you agree to our";
export const TERMS_AND_CONDITIONS = "Terms and Conditions";
export const AND = "&";
export const PRIVACY_POLICY = "Privacy Policy";
export const COST = (item) =>  `₹ ${item} /-`;
export const DISCOUNT_AMOUNT = (item) =>  `- ₹ ${item} /-`;