import { StyleSheet } from 'react-native';
import { BLUE_GRAY, CHARCOAL, COUPON_DARK_GREY, CYAN_BLUE, DARK_GRAY, DEEP_BLUE, GREEN, GREY70, INDIGO, ORANGE, WHITE } from '../../styles/colors'
import { FLEX_END, RIGHT, ROW, SPACE_BETWEEN, CENTER } from '../../styles/constants';
import { fonts } from '../../styles/fonts';

export const styles = StyleSheet.create({
    TextPrice: {
        marginLeft: "7%",
        marginTop: "4%",
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik500,
        fontSize: fonts.size.fontSize14,
    },
    QuantityView: {
        flexDirection: ROW,
    },
    QuantityNumber: {
        textAlign: RIGHT,
        flex: 1,
        marginHorizontal:25,
        marginTop: "5%",
        color: INDIGO,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize14,
        lineHeight:21,
    },
    QuantityViewNumber: {
        backgroundColor: ORANGE,
        alignSelf: FLEX_END
    },
    Quantity: {
        marginLeft: "7%",
        marginTop: "5.12%",
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize14,
    },
    line: {
        marginTop: "3.43%",
        borderWidth: 0.2,
        marginLeft: "7%",
        width: "85%",
        borderColor: GREY70,
    },
    orderPrice: {
        marginLeft: "7%",
        marginTop: "1.97%",
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize16,
    },
    OrderAmountDirection: {
        flexDirection: ROW,
        marginTop:'2.5%',
    },

    orderAmount: {
        textAlign: RIGHT,
        flex: 1,
        marginRight: "8%",
        marginTop: "2%",
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize16,
    },
    Input: {
        borderColor: GREY70,
        borderWidth: 1,
        borderRadius: 12,
        marginLeft: "7%",
        marginTop: 35,
        minHeight: 40,
        width: "86%",
    },
    Apply: {
        textAlign: RIGHT,
        flex: 1,
        marginLeft: 27,
        color: WHITE,
        marginTop: 10,

    },
    ApplyCoupon: {
        alignItems: CENTER,
        borderWidth: 0.5,
        borderRadius: 12,
        minHeight: 40,
        width: 100,
        marginTop: 35,
        alignSelf: CENTER,
        backgroundColor: ORANGE,
        borderColor: GREY70,
    },
    Amountpyable: {
        marginLeft: "7.1%",
        marginTop: "2.76%",
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik600,
        fontSize: fonts.size.fontSize16,
    },
    payableAmount: {
        textAlign: RIGHT,
        flex: 1,
        marginRight: "8%",
        marginTop: "2%",
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik600,
        fontSize: fonts.size.fontSize16,
    },
    touchableButton: {
        backgroundColor: ORANGE,
        marginTop: 40,
        marginLeft: 13,
        marginRight: 14,
        borderRadius: 8,
        minHeight: 48,
        alignItems: CENTER,
    },
    termsAndCondtion: {
        width: "60%",
        marginTop: "4.55%",
        marginLeft: "1.5%",
        marginRight: 56,
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize10,
    },
    checkBoxContainer: {
        marginTop: "2.5%",
        marginLeft: "4.90%",
        borderColor: CYAN_BLUE,
    },
    viewCoupon: {
        width: "85%",
        marginTop: "4.61%",
        flexDirection: ROW,
        justifyContent: SPACE_BETWEEN,
        borderWidth: 0.5,
        borderRadius: 12,
        height: 40,
        marginLeft: "7%",
        marginHorizontal: 15,
        borderRightColor: ORANGE,
        borderColor: COUPON_DARK_GREY,
    },
    textInputStyles: {
        marginLeft: "3.25%",
        marginBottom: 11,
        height: 40,
        width: 206,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize14,
    },
    applyStyles: {
        borderRadius: 12,
        width: "26%",
        backgroundColor: ORANGE,
        height: 40,
        justifyContent: CENTER,
        alignItems: CENTER,
    },
    applyButtonStyles: {
        color: WHITE,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize16,
        textAlign: CENTER,
    },
    TextPriceDiscount: {
        marginLeft: "7%",
        marginTop: "3.76%",
        color: CYAN_BLUE,
        fontFamily: fonts.family.rubik500,
        fontSize: fonts.size.fontSize14,
    },
    payableAmountDiscount: {
        textAlign: RIGHT,
        flex: 1,
        marginRight: "8%",
        marginTop: "3.76%",
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize14,
    },
    couponContainer: {
        flexDirection: ROW,
        justifyContent: SPACE_BETWEEN,
        padding: 5,
        marginVertical: 25,
        marginHorizontal: 16
    },
    crossStyle: {
        color: DARK_GRAY,
        fontFamily: fonts.family.rubik600,
        fontSize: fonts.size.fontSize16,
    },
    iconStyle: {
        color: CHARCOAL,
    },
    appliedStyle: {
        color: DEEP_BLUE,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize16,
    },
    descStyle: {
        height: 36,
        width: '60%',
        borderRadius: 5,
        paddingLeft: 16,
        paddingRight: 12,
        justifyContent: SPACE_BETWEEN,
        alignItems: CENTER,
        flexDirection: ROW,
        backgroundColor: BLUE_GRAY,
    },
    couponDiscountStyle: {
        height: 36,
        color: GREEN,
        paddingVertical: 10,
        fontFamily: fonts.family.rubik400,
        fontSize: fonts.size.fontSize14,
        paddingHorizontal: 5,
    },
})
