import {StyleSheet} from 'react-native';
import {
  BLACK,
  CYAN_BLUE,
  DARK_BLUE,
  GREEN,
  GREY,
  LIGHT_MERCURY,
  LIGHT_ORANGE,
  LIGHT_RED,
  ORANGE,
  PLATINUM,
  RED,
  RED_SHADE,
  VERY_PALE_WHITE,
  WHITE,
} from '../../../../styles/colors';
import {
  ABSOLUTE,
  CENTER,
  FLEX_END,
  ROW,
  SPACE_BETWEEN,
} from '../../../../styles/constants';
import {fonts} from '../../../../styles/fonts';

export const styles = StyleSheet.create({
  description: {
    marginTop: '5%',
    marginHorizontal: '4%',
  },
  description1: {
    marginVertical: '5%',
    marginHorizontal: '4%',
  },
  ScrollViewContainerStyle: {
    paddingBottom: '50%',
  },
  Header: {
    color: CYAN_BLUE,
    fontSize: fonts.size.fontSize14,
    fontFamily: fonts.family.rubik600,
  },
  textInputStyle: {
    borderBottomWidth: 1,
    borderColor: PLATINUM,
    backgroundColor: WHITE,
    marginBottom: 15,
    color: BLACK,
    fontSize: fonts.size.fontSize12,
    fontFamily: fonts.family.rubik400,
    marginTop: '5%',
    borderRadius: 6,
  },
  border: {
    marginHorizontal: '4%',
    shadowColor: GREY,
    elevation: 10,
    borderRadius: 10,
    backgroundColor: WHITE,
    height: 118,
  },
  familyView: {
    height: 90,
    marginHorizontal: '4%',
    marginBottom: '5%',
    shadowColor: GREY,
    elevation: 10,
    borderRadius: 10,
    backgroundColor: WHITE,
  },
  viewCont: {
    backgroundColor: LIGHT_ORANGE,
    height: 92,
    justifyContent: CENTER,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  confirmStyle: {
    backgroundColor: VERY_PALE_WHITE,
  },
  cancelledStyle: {
    backgroundColor: LIGHT_RED,
  },
  direction: {
    flexDirection: ROW,
    alignSelf: CENTER,
  },
  waitStyle: {
    color: ORANGE,
    marginTop: '5%',
    marginRight: '1%',
    marginLeft: '5%',
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize12,
  },
  StatusStyle: {
    color: ORANGE,
    marginTop: '5%',
    marginRight: '1%',
    marginLeft: '5%',
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize18,
  },
  numberSytle: {
    marginHorizontal: 8,
    color: WHITE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize10,
  },
  NameStyle: {
    marginTop: '5%',
    marginLeft: '15%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  ImageStyle: {
    flexDirection: ROW,
    marginLeft: '5%',
  },
  Image: {
    height: 48,
    width: 48,
    alignSelf: CENTER,
  },
  HospName: {
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize14,
    marginLeft: '5%',
    marginVertical: '5%',
  },
  FamilyName: {
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik500,
    fontSize: fonts.size.fontSize14,
    marginLeft: '5%',
    marginVertical: '5%',
  },
  RelationStyle: {
    color: ORANGE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
    marginLeft: '5%',
    marginBottom: '5%',
  },
  ContentStyle: {
    marginVertical: '5%',
    marginLeft: '15%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize10,
  },
  timeSlot: {
    backgroundColor: DARK_BLUE,
    borderBottomLeftRadius: 24,
    borderTopLeftRadius: 24,
    minHeight: 48,
    justifyContent: CENTER,
    alignItems: CENTER,
    position: ABSOLUTE,
    right: 0,
    width: 141,
    marginVertical: 22,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize10,
  },
  cancelStatus: {
    backgroundColor: RED_SHADE,
  },
  StatusBox: {
    flexDirection: ROW,
    alignItems: CENTER,
  },
  buttonStyle: {
    flexDirection: ROW,
    paddingHorizontal: 12,
    justifyContent: SPACE_BETWEEN,
  },
  buttonStyleDetails: {
    width: '45%',
    height: 48,
    marginVertical: 24,
    borderRadius: 8,
    justifyContent: CENTER,
    alignItems: CENTER,
    flexDirection: ROW,
    shadowColor: GREY,
    elevation: 10,
  },
  buttonTextStyle: {
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik700,
    fontSize: fonts.size.fontSize16,
    marginHorizontal: '4%',
  },
  statusBoxText: {
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize18,
    color: RED_SHADE,
    marginTop: 13,
    marginLeft: 17,
  },

  statusBoxInitiated: {
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize18,
    marginLeft: 17,
  },
  AppointmentId: {
    flexDirection: ROW,
    width: '100%',
  },
  AppointmentIdText: {
    marginTop: 17,
    marginLeft: 36,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
    color: DARK_BLUE,
  },
  customId: {
    marginTop: 5,
    marginLeft: 36,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize12,
    color: CYAN_BLUE,
  },
  appoitmentid: {
    marginTop: 8,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize10,
    marginLeft: 17,
    color: DARK_BLUE,
  },
  appoitmentidNumber: {
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize10,
    marginTop: 5,
    marginLeft: 17,
    color: CYAN_BLUE,
  },
  NameStyle: {
    marginTop: '5%',
    marginBottom: '5%',
    marginLeft: '15%',
    color: CYAN_BLUE,
    fontFamily: fonts.family.rubik600,
    fontSize: fonts.size.fontSize14,
  },
  Image: {
    height: 48,
    width: 48,
    alignSelf: CENTER,
  },
});
