import { StyleSheet } from 'react-native';
import { BLACK, CYAN_BLUE, DARK_BLUE, GREY, INDIGO_LIGHT, MARINER, MEDIUM_CARMINE, ORANGE, WHITE } from '../../styles/colors';
import { CENTER, COLUMN, ROW, SPACE_BETWEEN } from '../../styles/constants';
import { fonts } from '../../styles/fonts';
export const styles = StyleSheet.create({
  mainContainer: {
    marginHorizontal: 15,
    flex: 1,
  },
  headingStyle: {
    paddingLeft: 16,
    color: INDIGO_LIGHT,
    fontSize: fonts.size.fontSize16,
    fontFamily: fonts.family.rubik400,
    lineHeight: fonts.Height.lineHeight18,
    marginVertical: 18,
  },
  subHeadingStyle: {
    color: MARINER,
    fontSize: fonts.size.fontSize14,
    fontFamily: fonts.family.monsterrant500,
    lineHeight: fonts.Height.lineHeight18,
    marginBottom: 10,
  },
  selectInput: {
    color: BLACK,
    fontSize: fonts.size.fontSize12,
    fontFamily: fonts.family.monsterrant500,
    lineHeight: fonts.Height.lineHeight18,
  },
  subHeading2Style: {
    color: DARK_BLUE,
    fontSize: fonts.size.fontSize12,
    fontFamily: fonts.family.rubik500,
    lineHeight: fonts.Height.lineHeight18,
  },
  searchConatiner: {
    marginVertical: 10,
    marginHorizontal: 10,
    minHeight: 42,
    backgroundColor: WHITE,
    borderColor: BLACK,
    borderWidth: 0.5,
    borderRadius: 12,
    flexDirection: ROW,
    paddingHorizontal: 12,
    alignItems: CENTER,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    elevation: 2,
    zIndex: 10,
  },
  searchTextInputStyle: {
    flex: 1,
    fontSize: fonts.size.fontSize12,
    fontFamily: fonts.family.montserrat400,
    color: BLACK,
  },
  textInputStyle: {
    marginVertical: 10,
    marginHorizontal: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    paddingLeft: 15,
    borderWidth: 0.5,
    borderColor: BLACK,
    backgroundColor: WHITE,
    borderRadius: 12,
    color: DARK_BLUE,
    minHeight: 42,
    fontFamily: fonts.family.rubik400,
    fontSize: fonts.size.fontSize14,
    zIndex: 10,
  },
  CompleteView: {
    marginVertical: 12,
    minHeight: 48,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    borderWidth: 0.5,
    borderColor: '#686868',
    backgroundColor: '#F7F8F9',
    borderRadius: 10,
  },
  Top: {
    flexDirection: COLUMN,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  cardNameStyle: {
    color: BLACK,
    fontFamily: fonts.family.monsterrant500,
    fontSize: fonts.size.fontSize16,
    lineHeight: 24,
  },
  cardAddressStyle: {
    maxWidth: '80%',
    color: '#686868',
    fontFamily: fonts.family.monsterrant500,
    fontSize: fonts.size.fontSize12,
    lineHeight: 24,
  },
  subTextStyle: {
    flexDirection: ROW,
    marginTop: 4,
  },
  subTextBottomStyle: {
    flexDirection: ROW,
    marginBottom: 16,
    marginRight: '50%',
    paddingVertical: 6,
  },
  textStyle: {
    marginLeft: 8,
    color: MARINER,
    fontFamily: fonts.family.monsterrant500,
    fontSize: fonts.size.fontSize14,
  },
  suggestions: {
    marginTop: 8,
    fontFamily: fonts.family.montserrat600,
    fontSize: fonts.size.fontSize18,
    color: BLACK,
  },
  rowView: {
    flexDirection: ROW,
    alignItems: CENTER,
    justifyContent: SPACE_BETWEEN,
  },
});